name: firebase_function_and_admin_interop_example

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  firebase_functions_interop:
    git:
      url: git://github.com/Skquark/firebase-functions-interop
  firebase_admin_interop: ^2.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.3
  mockito: ^4.1.1
  # Needed to compile Dart to valid Node.js module.
  build_runner: ^1.9.0
  build_node_compilers: ^0.2.0